app:
  dao:
    user-email:
      methods:
        insert-certification: InsertCertification
        select-for-check-certification: SelectForCheckCertification
        delete-certification: DeleteCertification

