app:
  professor:
    params:
      user-name: UserName
      user-name-for-open: UserNameForOpen
      user-login-id: UserLoginID
      user-phone-num: UserPhoneNum
      user-phone: UserPhone
      user-email: UserEmail
      user-major: UserMajor
      email: Email
    
    urls:
      signup: /signup/signupProfessor
      mypage: /mypage/myPageProfessor
      modify: /mypage/modifyProfessor

