server:
  # port: 8081
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

management:
  endpoints:
    web:
      exposure:
        include: health,info


